intents:
  - affirm
  - deny
  - greet
  - goodbye
  - thanks
  - whoareyou
  - whattodo
  - request_weather
  - inform
  - stop
  - chitchat
  - first: {triggers: action_first}

session_config:
  carry_over_slots_to_new_session: true
  session_expiration_time: 60

slots:
  date_time:
    type: unfeaturized
    auto_fill: false
  address:
    type: unfeaturized
    auto_fill: false

entities:
  - date_time
  - address

actions:
  - utter_answer_affirm
  - utter_answer_deny
  - action_first
  - utter_answer_greet
  - utter_answer_goodbye
  - utter_answer_thanks
  - utter_answer_whoareyou
  - utter_answer_whattodo
  - utter_ask_date_time
  - utter_ask_address
  - action_default_fallback

forms:
  - weather_form
  - number_form

responses:
  utter_answer_affirm:
    - text: "嗯嗯，好的！"
    - text: "嗯嗯，很开心能够帮您解决问题~"
    - text: "嗯嗯，还需要什么我能够帮助您的呢？"

  utter_answer_greet:
    - text: "您好！请问有什么可以帮您的？"
    - text: "hello master！"
    - text: "您好！很高兴为您服务。请说出您要查询的功能？"

  utter_answer_goodbye:
    - text: "再见(^_^)/~~"
    - text: "拜拜(^_^)/~~"
    - text: "虽然我有万般舍不得，但是天下没有不散的宴席~祝您安好！"
    - text: "期待下次再见！"
    - text: "嗯嗯，下次需要时随时记得我哟~"
    - text: "see you!"
    - text: "再见，祝您身体健康～"
    - text: "拜拜，希望我有帮到您～"
    - text: "886～"
    - text: "告辞～"
    - text: "bye bye～"
    - text: "bye ～"


  utter_answer_deny:
    - text: "主人，您不开心吗？不要离开我哦o(╯□╰)o"
    - text: "怎么了，主人？"

  utter_answer_thanks:
    - text: "嗯呢。不用客气~"
    - text: "这是我应该做的，主人~"
    - text: "嗯嗯，合作愉快！"

  utter_answer_whoareyou:
    - text: "您好！我是小瑞呀，您的AI智能助理"

  utter_answer_whattodo:
    - text: "您好！很高兴为您服务，我目前支持天气查询，闲聊。"

  utter_ask_date_time:
    - text: "请问您要查询哪一天的天气？"

  utter_ask_address:
    - text: "请问您要查下哪里的天气？"

  utter_default:
    - text: "不好意思，没听懂，小瑞还在学习中，请先换种问法吧~"

  utter_ask_continue:
    - text: "请问您还要继续吗?"
    - text: "不好意思，小瑞学习不够，会继续努力学习的~"
    - text: "不好意思，惹你生气了，抱抱~"

  utter_noworries:
    - text: "不用客气^_^"
    - text: "没事啦，小事一件！"
    - text: "不客气哈，都是老朋友了=^_^="

  utter_chitchat:
    - text: "呃呃呃呃呃"
    - text: "您这是在尬聊吗？"
    - text: "我不知道说啥了"