action_endpoint:
  url: "http://localhost:5055/webhook"

tracker_store:
    type: SQL
    dialect: "mysql+pymysql"  # the dialect used to interact with the db
    url: "localhost"  # (optional) host of the sql db, e.g. "localhost"
    port: 3306
    db: "doctor_friende"  # path to your db
    username: "root"  # username used for authentication
    password: "root"  # password used for authentication